### ISSUE TITLE
Default output file name should be composed from title and subtitle

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/reports-template#2]
```
title: "Title" # Title of the document
subtitle: "Subtitle" # Subtitle of the document. May be left empty
author: "" # Author of the document. May be left empty
institute: "ESQlabs GmbH"
date: "now"
date-format: "YYYY-MM-DD HH:mm:ss" 
params:  
  # If set to TRUE, only static content of the report will be generated,
  # i.e., R code will not be executed
  loadPreSimulatedResults: TRUE # If `TRUE`, results will be loaded from the folder specified in `loadResultsFolder`
  loadResultsFolder: "PB" # Sub-folder where simulated results is located, in case `loadPreSimulatedResults` is `TRUE`. If `NULL`, default results folder as specified in `ProjectConfiguration` is used.
  saveResultsFolder: NULL # Sub-folder where the results will be stored. If `NULL`, a folder in the "Results" folder with current data name will be created.
output-file: "ms-report-template" #Name of the output file.
```

`output-file` should be `paste0(title, " - ", subtitle).
